[build]
  base = "/"
  command = "npx turbo build"
  publish = "apps/web/.next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.22"

# Production context
[context.production]
  command = "yarn global add turbo && yarn install && yarn build"
  environment = { NODE_ENV = "production" }

# Deploy Preview context
[context.deploy-preview]
  command = "yarn global add turbo && yarn install && yarn build"
  environment = { NODE_ENV = "development" }

# Branch Deploy context
[context.branch-deploy]
  command = "yarn global add turbo && yarn install && yarn build"
  environment = { NODE_ENV = "staging" }

[[plugins]]
  package = "@netlify/plugin-nextjs" 